= RobotC Language Specification
Document Author <email@none.none>
:toc:
:numbered:

Specicially for the Cortex (Vex) implementation. Lacking an authoritative source for the RobotC language specification, much of this was derived from http://www.robotc.net/wikiarchive/General.

== Data Types

bool:: { true, false }; { non-zero, 0 } (not sure what the underlying data type is)
byte:: -128 to 127 (seems to be 8 bit signed integer)
char:: -128 to 127; 'x' where x is a character (seems to be 8 bit signed integer)
float::
    This seems to be a 25 bit value, but the semantics are not clear.
```
    0.####  0.0000 to +2,048.0000 (2^11 . 0000 ; 11 bits + 14 bits)
    0.###   0.000 to +32,768.000 (2^15 . 000 ; 15 bits + 10 bits)
    0.##    0.00 to +262,144.00 (2^18 . 00 ; 18 bits + 7 bits)
    0.#     0.0 to +2,097,200.0 (~ 2^21 . 0 ; 21 bits + 4 bits)
```
long:: -2,147,483,648 to 2,147,483,647 (seems to be a 32 bit signed integer)
int:: -32,768 to 32,767 (seems to be 16 bit signed integer)
short:: -32,768 to 32,767 (seems to be 16 bit signed integer)
string:: "sequence of characters" (unspecified semantics)
word:: -32,768 to 32,767 (seems to be 16 bit signed integer)
ubyte:: 0 to 255 (seems to be 8 bit unsigned integer)
void:: void (for function return)

== Control Structures

=== do while

```
do
{
    statements
} while (expression)
```

=== for

```
for ( expression1; expression2; expression3 )
{
    statements
}
```

=== if else

```
if (expression)
{
    statement1
}
else
{
    statement2
}
```

=== switch case

```
switch (expression)
{
    case label1:
        statements1;
    case label2:
        statements2;
        break;
    default:
        statements3;
}
```

=== while

```
while (expression)
{
    statements
}
```

== Enumerations

These are types with predefined possible values.

=== TI2CStatus
|===
| NO_ERR | 0
| STAT_COMM_PENDING | 32
| ERR_COMM_CHAN_NOT_READY | -32
| ERR_COMM_BUS_ERR | -35
|===

=== tSensors
|===
| in1 | 0
| in2 | 1
| in3 | 2
| in4 | 3
| in5 | 4
| in6 | 5
| in7 | 6
| in8 | 7
| dgtl1 | 8
| dgtl2 | 9
| dgtl3 | 10
| dgtl4 | 11
| dgtl5 | 12
| dgtl6 | 13
| dgtl7 | 14
| dgtl8 | 15
| dgtl9 | 16
| dgtl10 | 17
| dgtl11 | 18
| dgtl12 | 19
| I2C_1 | 20
| I2C_2 | 21
| I2C_3 | 22
| I2C_4 | 23
| I2C_5 | 24
| I2C_6 | 25
| I2C_7 | 26
| I2C_8 | 27
|===

=== TSounds
|===
| soundBlip | 0
| soundBeepBeep | 1
| soundDownwardTones | 2
| soundUpwardTones | 3
| soundLowBuzz | 4
| soundFastUpwardTones | 5
| soundShortBlip | 6
| soundException | 7
| soundLowBuzzShort | 8
|===

=== TTimers
|===
| T1 | 0
| T2 | 1
| T3 | 2
| T4 | 3
|===

=== TUARTs
|===
| uartOne | 0
| uartTwo | 1
|===

=== TVexJoysticks
|===
| Ch1 | 0
| Ch2 | 1
| Ch3 | 2
| Ch4 | 3
| Ch5 | 4
| Ch6 | 5
| Btn5U | Btn5D + 1
| Btn5D | 15
| Btn6U | Btn5D + 3
| Btn6D | Btn5D + 2
| Btn7U | Btn5D + 10
| Btn7D | Btn5D + 8
| Btn7L | Btn5D + 9
| Btn7R | Btn5D + 11
| Btn8U | Btn5D + 6
| Btn8D | Btn5D + 4
| Btn8L | Btn5D + 5
| Btn8R | Btn5D + 7
| AccelX | 38
| AccelY | AccelX + 1
| AccelZ | AccelX + 2
| Ch1Xmtr2 | 6
| Ch2Xmtr2 | 7
| Ch3Xmtr2 | 8
| Ch4Xmtr2 | 9
| Ch5Xmtr2 | 10
| Ch6Xmtr2 | 11
| Btn5UXmtr2 | Btn5DXmtr2 + 1
| Btn5DXmtr2 | 26
| Btn6UXmtr2 | Btn5DXmtr2 + 3
| Btn6DXmtr2 | Btn5DXmtr2 + 2
| Btn7UXmtr2 | Btn5DXmtr2 + 10
| Btn7DXmtr2 | Btn5DXmtr2 + 8
| Btn7LXmtr2 | Btn5DXmtr2 + 9
| Btn7RXmtr2 | Btn5DXmtr2 + 11
| Btn8UXmtr2 | Btn5DXmtr2 + 6
| Btn8DXmtr2 | Btn5DXmtr2 + 4
| Btn8LXmtr2 | Btn5DXmtr2 + 5
| Btn8RXmtr2 | Btn5DXmtr2 + 7
| AccelXXmtr2 | 41
| AccelYXmtr2 | AccelXXmtr2 + 1
| AccelZXmtr2 | AccelXXmtr2 + 2
|===

=== TVexReceiverState
|===
| vrNoXmiters | 0 (No transmitters connected)
| vrXmit1 | 0x01 (1: Transmitter 1 connected)
| vrXmit2 | 0x02 (1: Transmitter 2 connected)
| vrBit2 | 0x04 (unused)
| vrCompetitionSwitch | 0x08 (0: No Comp Switch, 1: Competition Switch attached)
| vrResetSlave | 0x10 (unused)
| vrGameController | 0x20 (0: Legacy75MHz, 1: Game Controller)
| vrAutonomousMode | 0x40 (0: Driver Control, 1: Autonomous Mode)
| vrDisabled | 0x80 (0: Enabled, 1: Disabled)
|===

== Debug Windows

Global Variables::
    ```void writeDebugStreamLine(const string sFormatString, ...)
    ```
Local Variables::
    ```#pragma DebuggerWindows("Locals")
    ```
Debug Stream::
    ```#pragma DebuggerWindows("debugStream")
    ```
Joystick Control - Basic::
    ```#pragma DebuggerWindows("joystickSimple")
    ```

=== Debug Stream

```
void writeDebugStreamLine(const string sFormatString, ...)
```

== Math

```
float abs(const float input)
float acos(const float Cosine)
float asin(const float Sine)
float atan(const float Tangent)
float atof ( string str )
long atoi ( string str )
float ceil(const float input)
float cos(const float fRadians)
float cosDegrees(const float fDegrees)
float degreesToRadians(const float fDegrees)
float exp(const float input)
float floor(const float input)
float log(const float input)
float log10(const float input)
const float PI = 3.14159265358979323846264338327950288419716939937510
float pow(const float base, const float exponent)
short radiansToDegrees(const float fRadians)
word rand() // 0 to at least 32,767
long randLong() // 0 to at least 2,147,483,647
short sgn(const float input) // {-1, 0, 1}
float sin(const float fRadians)
float sinDegrees(const float fDegrees)
void srand(const long nSeedValue)
float sqrt(const float input)
```

== Operations

http://www.robotc.net/wikiarchive/Order_Of_Operations

== Preprocessor Defines

http://www.robotc.net/wikiarchive/Preprocessor_Defines

== String Functions

http://www.robotc.net/wikiarchive/General/Strings

== Functions and Variables

http://www.robotc.net/wikiarchive/VEX2_Functions_and_Variables
